language: bash
sudo: required
services:
- docker
cache:
  directories:
  - "${HOME}/google-cloud-sdk"
before_install:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in akvo-lumen-acbe302a69ce.json.enc -out akvo-lumen-acbe302a69ce.json -d
- export GCLOUD_ACCOUNT_FILE=$(pwd)/akvo-lumen-acbe302a69ce.json
- if [[ ! -f "${HOME}/google-cloud-sdk/bin/gcloud" ]]; then rm -rf "${HOME}/google-cloud-sdk";
  curl https://sdk.cloud.google.com | bash > /dev/null; fi
script:
- ./testing-travis.sh
env:
  global:
  - PATH=${HOME}/google-cloud-sdk/bin:$PATH
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
